import { 
  Student, 
  Parent, 
  Teacher, 
  ClassRoom, 
  AttendanceRecord, 
  GradeRecord, 
  TimetableSlot, 
  PaymentRecord, 
  CanteenDay, 
  TransportRoute, 
  WhatsAppMessageLog, 
  TunisianSchool,
  HomeworkItem
} from './types';

export const mockTunisianSchools: TunisianSchool[] = [
  {
    id: 'sch-1',
    name: 'Complexe Scolaire Carthage Byrsa',
    nameAr: 'المجمع المدرسي قرطاج بيرصا',
    type: 'complexe',
    category: 'prive',
    governorate: 'Tunis',
    governorateAr: 'تونس',
    delegation: 'Délégation Régionale de l\'Éducation Tunis 1',
    delegationAr: 'المندوبية الجهوية للتربية تونس 1',
    city: 'Carthage Byrsa',
    cityAr: 'قرطاج بيرصا',
    address: '22 Avenue de la République, Carthage Byrsa, Tunis',
    addressAr: '22 شارع الجمهورية، قرطاج بيرصا، تونس',
    phone: '+216 71 732 450',
    email: 'contact@carthage-ecoles.tn',
    directorName: 'M. Hichem Ben Salem',
    directorNameAr: 'السيد هشام بن سالم',
    studentCount: 680,
    classesCount: 26,
    successRate: 98.4,
    isPartner: true,
    motto: 'Excellence Pédagogique & Réussite aux Concours Nationaux',
    mottoAr: 'التميز البيداغوجي والنجاح في المناظرات الوطنية'
  },
  {
    id: 'sch-2',
    name: 'Lycée Pilote Bourguiba de Tunis',
    nameAr: 'المعهد النموذجي الحبيب بورقيبة بتونس',
    type: 'lycee',
    category: 'pilote',
    governorate: 'Tunis',
    governorateAr: 'تونس',
    delegation: 'Délégation Régionale de l\'Éducation Tunis 1',
    delegationAr: 'المندوبية الجهوية للتربية تونس 1',
    city: 'Tunis Centre',
    cityAr: 'تونس العاصمة',
    address: 'Avenue du 9 Avril 1938, Tunis',
    addressAr: 'شارع 9 أفريل 1938، تونس',
    phone: '+216 71 560 120',
    email: 'direction@lpbt.edunet.tn',
    directorName: 'Mme Leïla Trabelsi',
    directorNameAr: 'السيدة ليلى الطرابلسي',
    studentCount: 1120,
    classesCount: 38,
    successRate: 100.0,
    isPartner: true,
    motto: 'Pépinière des Élites & Premier au Baccalauréat National',
    mottoAr: 'معقل النخبة والمتفوقين في امتحان الباكالوريا'
  },
  {
    id: 'sch-3',
    name: 'Groupe Scolaire International Les Berges du Lac',
    nameAr: 'المجمع المدرسي الدولي ضفاف البحيرة',
    type: 'complexe',
    category: 'international',
    governorate: 'Tunis',
    governorateAr: 'تونس',
    delegation: 'Délégation Régionale Tunis 2',
    delegationAr: 'المندوبية الجهوية تونس 2',
    city: 'Les Berges du Lac 2',
    cityAr: 'ضفاف البحيرة 2',
    address: 'Rue de l\'Île de Djerba, Les Berges du Lac 2, Tunis',
    addressAr: 'نهج جزيرة جربة، ضفاف البحيرة 2، تونس',
    phone: '+216 71 960 800',
    email: 'contact@ecole-lac.tn',
    directorName: 'M. Samir Gharbi',
    directorNameAr: 'السيد سمير الغربي',
    studentCount: 840,
    classesCount: 32,
    successRate: 99.2,
    isPartner: true,
    motto: 'Ouverture Multilingue & Enseignement Numérique Avancé',
    mottoAr: 'انفتاح لغوي وتعليم رقمي متطور'
  },
  {
    id: 'sch-4',
    name: 'Institution Éducative Ennasr & El Menzah',
    nameAr: 'مؤسسة النصر والمنزه التربوية',
    type: 'complexe',
    category: 'prive',
    governorate: 'Ariana',
    governorateAr: 'أريانة',
    delegation: 'Délégation Régionale de l\'Éducation d\'Ariana',
    delegationAr: 'المندوبية الجهوية للتربية بأريانة',
    city: 'Ennasr 2',
    cityAr: 'النصر 2',
    address: 'Avenue Hédi Nouira, Ennasr 2, Ariana',
    addressAr: 'شارع الهادي نويرة، النصر 2، أريانة',
    phone: '+216 70 830 500',
    email: 'info@ennasr-menzah.tn',
    directorName: 'Mme Sonia Dridi',
    directorNameAr: 'السيدة سنية الدريدي',
    studentCount: 720,
    classesCount: 28,
    successRate: 97.8,
    isPartner: true,
    motto: 'Épanouissement de l\'Élève & Encadrement Personnalisé',
    mottoAr: 'تفتح التلميذ وإحاطة بيداغوجية مشخصة'
  },
  {
    id: 'sch-5',
    name: 'École & Collège Ibn Khaldoun - Sfax',
    nameAr: 'مدرسة وإعدادية ابن خلدون - صفاقس',
    type: 'college',
    category: 'prive',
    governorate: 'Sfax',
    governorateAr: 'صفاقس',
    delegation: 'Délégation Régionale Sfax 1',
    delegationAr: 'المندوبية الجهوية صفاقس 1',
    city: 'Sfax Ville',
    cityAr: 'صفاقس المدينة',
    address: 'Route de Téniour Km 2, Sfax',
    addressAr: 'طريق تنيور كلم 2، صفاقس',
    phone: '+216 74 240 100',
    email: 'sfax@ibnkhaldoun.tn',
    directorName: 'M. Moncef Ayari',
    directorNameAr: 'السيد منصف العياري',
    studentCount: 910,
    classesCount: 34,
    successRate: 98.9,
    isPartner: true,
    motto: 'Tradition de Rigueur & Pôle Scientifique d\'Excellence',
    mottoAr: 'عراقة وانضباط وقطب علمي متميز'
  },
  {
    id: 'sch-6',
    name: 'Complexe Scolaire Sousse Corniche',
    nameAr: 'المجمع المدرسي سوسة كورنيش',
    type: 'complexe',
    category: 'prive',
    governorate: 'Sousse',
    governorateAr: 'سوسة',
    delegation: 'Délégation Régionale de l\'Éducation de Sousse',
    delegationAr: 'المندوبية الجهوية للتربية بسوسة',
    city: 'Sousse Boujaafar',
    cityAr: 'سوسة بوجعفر',
    address: 'Boulevard Taieb Mhiri, Sousse Corniche',
    addressAr: 'شارع الطيب المهيري، كورنيش سوسة',
    phone: '+216 73 228 300',
    email: 'contact@sousse-ecoles.tn',
    directorName: 'Mme Salma Jaziri',
    directorNameAr: 'السيدة سلمى الجزيري',
    studentCount: 650,
    classesCount: 24,
    successRate: 97.5,
    isPartner: true,
    motto: 'Cadre Méditerranéen & Réussite Éducative',
    mottoAr: 'إطار متميز ونجاح تربوي مضمون'
  }
];

export const mockParents: Parent[] = [
  {
    id: 'par-1',
    name: 'Karim Ben Romdhane',
    nameAr: 'كريم بن رمضان',
    phone: '+216 98 123 456',
    email: 'k.benromdhane@gmail.com',
    password: 'parent123',
    address: '24 Résidence Byrsa, Carthage, Tunis',
    addressAr: '24 إقامة بيرصا، قرطاج، تونس',
    childrenIds: ['stu-1', 'stu-4'],
    relationship: 'Père',
    relationshipAr: 'أب',
    whatsappOptIn: true
  },
  {
    id: 'par-2',
    name: 'Salma Trabelsi',
    nameAr: 'سلمى الطرابلسي',
    phone: '+216 20 234 567',
    email: 'salma.trabelsi@topnet.tn',
    password: 'parent123',
    address: '88 Avenue Hédi Nouira, Ennasr 2, Ariana',
    addressAr: '88 شارع الهادي نويرة، النصر 2، أريانة',
    childrenIds: ['stu-2'],
    relationship: 'Mère',
    relationshipAr: 'أم',
    whatsappOptIn: true
  },
  {
    id: 'par-3',
    name: 'Tarek Jaziri',
    nameAr: 'طارق الجزيري',
    phone: '+216 50 345 678',
    email: 'tarek.jaziri@gnet.tn',
    password: 'parent123',
    address: '15 Route de Téniour Km 1.5, Sfax',
    addressAr: '15 طريق تنيور كلم 1.5، صفاقس',
    childrenIds: ['stu-3'],
    relationship: 'Père',
    relationshipAr: 'أب',
    whatsappOptIn: true
  },
  {
    id: 'par-4',
    name: 'Nawal Slama',
    nameAr: 'نوال سلامة',
    phone: '+216 22 456 789',
    email: 'nawal.slama@gmail.com',
    password: 'parent123',
    address: '42 Boulevard Taïeb Mhiri, Sousse',
    addressAr: '42 شارع الطيب المهيري، سوسة',
    childrenIds: ['stu-5'],
    relationship: 'Mère',
    relationshipAr: 'أم',
    whatsappOptIn: true
  }
];

export const mockClasses: ClassRoom[] = [
  {
    id: 'cls-1',
    name: '6ème Année de Base (Concours Pilote - A)',
    nameAr: 'السنة السادسة أساسي (مناظرة النموذجي - أ)',
    level: 'Primaire',
    roomNumber: 'Salle Carthage 101',
    mainTeacherId: 'tch-1',
    studentCount: 26,
    capacity: 30
  },
  {
    id: 'cls-2',
    name: '9ème Année de Base (Concours Neuvième)',
    nameAr: 'السنة التاسعة أساسي (مناظرة النوفيام)',
    level: 'Collège',
    roomNumber: 'Salle Byrsa 204',
    mainTeacherId: 'tch-2',
    studentCount: 28,
    capacity: 30
  },
  {
    id: 'cls-3',
    name: '4ème Année Baccalauréat Mathématiques',
    nameAr: 'السنة الرابعة باكالوريا رياضيات',
    level: 'Lycée',
    roomNumber: 'Laboratoire Ibn Khaldoun',
    mainTeacherId: 'tch-4',
    studentCount: 24,
    capacity: 28
  },
  {
    id: 'cls-4',
    name: '3ème Année de Base (Primaire - B)',
    nameAr: 'السنة الثالثة أساسي (ابتدائي - ب)',
    level: 'Primaire',
    roomNumber: 'Salle Didon 102',
    mainTeacherId: 'tch-3',
    studentCount: 22,
    capacity: 28
  }
];

export const mockTeachers: Teacher[] = [
  {
    id: 'tch-1',
    name: 'Moncef Ayari',
    nameAr: 'منصف العياري',
    subject: 'Langue Arabe & Éducation Civique',
    subjectAr: 'اللغة العربية والتربية المدنية',
    phone: '+216 98 112 233',
    email: 'm.ayari@carthage-ecoles.tn',
    password: 'prof123',
    classes: ['6ème Année de Base (Concours Pilote - A)', '3ème Année de Base (Primaire - B)'],
    photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=250'
  },
  {
    id: 'tch-2',
    name: 'Sonia Dridi',
    nameAr: 'سنية الدريدي',
    subject: 'Français & Littérature',
    subjectAr: 'اللغة الفرنسية والآداب',
    phone: '+216 20 223 344',
    email: 's.dridi@carthage-ecoles.tn',
    password: 'prof123',
    classes: ['9ème Année de Base (Concours Neuvième)', '4ème Année Baccalauréat Mathématiques'],
    photo: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=250'
  },
  {
    id: 'tch-3',
    name: 'Béchir Slama',
    nameAr: 'بشير سلامة',
    subject: 'Mathématiques & Logique',
    subjectAr: 'الرياضيات والتفكير المنطقي',
    phone: '+216 50 334 455',
    email: 'b.slama@carthage-ecoles.tn',
    password: 'prof123',
    classes: ['6ème Année de Base (Concours Pilote - A)', '9ème Année de Base (Concours Neuvième)'],
    photo: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=250'
  },
  {
    id: 'tch-4',
    name: 'Rim Mahjoub',
    nameAr: 'ريم المحجوب',
    subject: 'Sciences Physiques & SVT',
    subjectAr: 'العلوم الفيزيائية وعلوم الحياة',
    phone: '+216 22 445 566',
    email: 'r.mahjoub@carthage-ecoles.tn',
    password: 'prof123',
    classes: ['9ème Année de Base (Concours Neuvième)', '4ème Année Baccalauréat Mathématiques'],
    photo: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=250'
  }
];

export const mockStudents: Student[] = [
  {
    id: 'stu-1',
    matricule: 'TUN-2024-001',
    firstName: 'Rayan',
    lastName: 'Ben Romdhane',
    firstNameAr: 'ريان',
    lastNameAr: 'بن رمضان',
    classId: 'cls-1',
    className: '6ème Année de Base (Concours Pilote - A)',
    classNameAr: 'السنة السادسة أساسي (مناظرة النموذجي - أ)',
    parentId: 'par-1',
    photo: 'https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=250',
    birthDate: '2013-05-12',
    gender: 'M',
    bloodType: 'O+',
    canteenSubscribed: true,
    transportSubscribed: true,
    transportRouteId: 'bus-1',
    attendanceRate: 98.2,
    averageGrade: 18.25
  },
  {
    id: 'stu-2',
    matricule: 'TUN-2024-002',
    firstName: 'Salma',
    lastName: 'Trabelsi',
    firstNameAr: 'سلمى',
    lastNameAr: 'الطرابلسي',
    classId: 'cls-2',
    className: '9ème Année de Base (Concours Neuvième)',
    classNameAr: 'السنة التاسعة أساسي (مناظرة النوفيام)',
    parentId: 'par-2',
    photo: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=250',
    birthDate: '2010-09-24',
    gender: 'F',
    bloodType: 'A+',
    canteenSubscribed: true,
    transportSubscribed: true,
    transportRouteId: 'bus-2',
    attendanceRate: 95.0,
    averageGrade: 18.6
  },
  {
    id: 'stu-3',
    matricule: 'TUN-2024-003',
    firstName: 'Youssef',
    lastName: 'Jaziri',
    firstNameAr: 'يوسف',
    lastNameAr: 'الجزيري',
    classId: 'cls-1',
    className: '6ème Année de Base (Concours Pilote - A)',
    classNameAr: 'السنة السادسة أساسي (مناظرة النموذجي - أ)',
    parentId: 'par-3',
    photo: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=250',
    birthDate: '2013-11-03',
    gender: 'M',
    bloodType: 'B+',
    canteenSubscribed: false,
    transportSubscribed: true,
    transportRouteId: 'bus-1',
    attendanceRate: 92.5,
    averageGrade: 16.4
  },
  {
    id: 'stu-4',
    matricule: 'TUN-2024-004',
    firstName: 'Nour',
    lastName: 'Ben Romdhane',
    firstNameAr: 'نور',
    lastNameAr: 'بن رمضان',
    classId: 'cls-4',
    className: '3ème Année de Base (Primaire - B)',
    classNameAr: 'السنة الثالثة أساسي (ابتدائي - ب)',
    parentId: 'par-1',
    photo: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=250',
    birthDate: '2016-02-18',
    gender: 'F',
    bloodType: 'O+',
    canteenSubscribed: true,
    transportSubscribed: true,
    transportRouteId: 'bus-1',
    attendanceRate: 100.0,
    averageGrade: 19.3
  },
  {
    id: 'stu-5',
    matricule: 'TUN-2024-005',
    firstName: 'Ahmed',
    lastName: 'Slama',
    firstNameAr: 'أحمد',
    lastNameAr: 'سلامة',
    classId: 'cls-3',
    className: '4ème Année Baccalauréat Mathématiques',
    classNameAr: 'السنة الرابعة باكالوريا رياضيات',
    parentId: 'par-4',
    photo: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=250',
    birthDate: '2007-07-30',
    gender: 'M',
    bloodType: 'AB+',
    canteenSubscribed: true,
    transportSubscribed: false,
    attendanceRate: 91.5,
    averageGrade: 17.1
  }
];

export const mockAttendance: AttendanceRecord[] = [
  {
    id: 'att-1',
    studentId: 'stu-3',
    date: '2025-02-18',
    timeSlot: '08:00 - 10:00',
    status: 'absent',
    subject: 'Mathématiques',
    subjectAr: 'الرياضيات',
    reason: 'Rendez-vous médical certifié',
    reasonAr: 'موعد طبي مع شهادة',
    isJustified: true,
    notifiedWhatsapp: true,
    submittedByTeacherId: 'tch-3',
    submittedByTeacherName: 'Béchir Slama',
    submittedByTeacherNameAr: 'بشير سلامة',
    submittedAt: '2025-02-18T08:15:00Z',
    adminValidated: true,
    adminValidatedAt: '2025-02-18T08:45:00Z',
    adminNote: 'Certificat médical présenté à la vie scolaire'
  },
  {
    id: 'att-2',
    studentId: 'stu-2',
    date: '2025-02-17',
    timeSlot: '08:00 - 08:30',
    status: 'late',
    subject: 'Français',
    subjectAr: 'الفرنسية',
    reason: 'Embouteillage échangeur Berges du Lac',
    reasonAr: 'ازدحام مروري بمحول البحيرة',
    isJustified: true,
    notifiedWhatsapp: true,
    submittedByTeacherId: 'tch-2',
    submittedByTeacherName: 'Sonia Dridi',
    submittedByTeacherNameAr: 'سنية الدريدي',
    submittedAt: '2025-02-17T08:35:00Z',
    adminValidated: true,
    adminValidatedAt: '2025-02-17T09:10:00Z',
    adminNote: 'Billet d\'entrée en classe délivré par la surveillance générale'
  },
  {
    id: 'att-3',
    studentId: 'stu-5',
    date: '2025-02-14',
    timeSlot: '14:00 - 16:00',
    status: 'absent',
    subject: 'Sciences Physiques',
    subjectAr: 'العلوم الفيزيائية',
    reason: 'Non justifié',
    reasonAr: 'غير مبرر',
    isJustified: false,
    notifiedWhatsapp: true,
    submittedByTeacherId: 'tch-4',
    submittedByTeacherName: 'Rim Mahjoub',
    submittedByTeacherNameAr: 'ريم المحجوب',
    submittedAt: '2025-02-14T14:10:00Z',
    adminValidated: true,
    adminValidatedAt: '2025-02-14T14:30:00Z',
    adminNote: 'Parent contacté par la direction'
  }
];

export const mockGrades: GradeRecord[] = [
  {
    id: 'grd-1',
    studentId: 'stu-1',
    subject: 'Mathématiques',
    subjectAr: 'الرياضيات',
    examType: 'Devoir de Contrôle 1',
    examTypeAr: 'فرض مراقبة 1',
    score: 18.5,
    maxScore: 20,
    coefficient: 3,
    date: '2025-02-14',
    teacherRemarks: 'Excellent raisonnement arithmétique et géométrie irréprochable.',
    teacherRemarksAr: 'استدلال حسابي ممتاز وهندسة نموذجية.'
  },
  {
    id: 'grd-2',
    studentId: 'stu-1',
    subject: 'Langue Arabe',
    subjectAr: 'اللغة العربية',
    examType: 'Devoir de Synthèse',
    examTypeAr: 'فرض تأليفي',
    score: 17.5,
    maxScore: 20,
    coefficient: 3,
    date: '2025-02-10',
    teacherRemarks: 'Excellente production d\'écrit et grammaire soignée.',
    teacherRemarksAr: 'إنشاء متميز وسلامة لغوية ونحوية ملحوظة.'
  },
  {
    id: 'grd-3',
    studentId: 'stu-1',
    subject: 'Français',
    subjectAr: 'الفرنسية',
    examType: 'Devoir de Contrôle 2',
    examTypeAr: 'فرض مراقبة 2',
    score: 18.0,
    maxScore: 20,
    coefficient: 2,
    date: '2025-02-05',
    teacherRemarks: 'Très bonne maîtrise du vocabulaire et syntaxe claire.',
    teacherRemarksAr: 'تمكن ممتاز من المعجم وبناء الجمل.'
  },
  {
    id: 'grd-4',
    studentId: 'stu-1',
    subject: 'Éveil Scientifique & Technologie',
    subjectAr: 'الإيقاظ العلمي والتكنولوجيا',
    examType: 'Devoir de Synthèse',
    examTypeAr: 'فرض تأليفي',
    score: 19.0,
    maxScore: 20,
    coefficient: 2,
    date: '2025-02-12',
    teacherRemarks: 'Grande curiosité scientifique et rigueur dans les expériences.',
    teacherRemarksAr: 'فضول علمي ودقة في إنجاز التجارب.'
  },
  {
    id: 'grd-5',
    studentId: 'stu-2',
    subject: 'Sciences Physiques',
    subjectAr: 'العلوم الفيزيائية',
    examType: 'Devoir de Synthèse',
    examTypeAr: 'فرض تأليفي',
    score: 19.0,
    maxScore: 20,
    coefficient: 4,
    date: '2025-02-11',
    teacherRemarks: 'Brillante copie pour le Concours Neuvième, notions maîtrisées.',
    teacherRemarksAr: 'ورقة ممتازة تؤهل لمناظرة النوفيام.'
  },
  {
    id: 'grd-6',
    studentId: 'stu-5',
    subject: 'Mathématiques Bac',
    subjectAr: 'رياضيات الباكالوريا',
    examType: 'Devoir de Synthèse',
    examTypeAr: 'فرض تأليفي',
    score: 17.5,
    maxScore: 20,
    coefficient: 4,
    date: '2025-02-08',
    teacherRemarks: 'Niveau prometteur pour la mention Très Bien au Baccalauréat.',
    teacherRemarksAr: 'مستوى واعد للحصول على ملاحظة حسن جداً في الباكالوريا.'
  }
];

export const mockTimetable: TimetableSlot[] = [
  {
    id: 'tt-1',
    classId: 'cls-1',
    day: 'monday',
    timeSlot: '08:00 - 10:00',
    subject: 'Mathématiques',
    subjectAr: 'الرياضيات',
    teacherName: 'Béchir Slama',
    teacherNameAr: 'بشير سلامة',
    room: 'Salle Carthage 101',
    color: 'border-blue-500 bg-blue-50 text-blue-800'
  },
  {
    id: 'tt-2',
    classId: 'cls-1',
    day: 'monday',
    timeSlot: '10:15 - 12:00',
    subject: 'Langue Arabe',
    subjectAr: 'اللغة العربية',
    teacherName: 'Moncef Ayari',
    teacherNameAr: 'منصف العياري',
    room: 'Salle Carthage 101',
    color: 'border-emerald-500 bg-emerald-50 text-emerald-800'
  },
  {
    id: 'tt-3',
    classId: 'cls-1',
    day: 'monday',
    timeSlot: '14:00 - 16:00',
    subject: 'Français',
    subjectAr: 'الفرنسية',
    teacherName: 'Sonia Dridi',
    teacherNameAr: 'سنية الدريدي',
    room: 'Salle Carthage 101',
    color: 'border-purple-500 bg-purple-50 text-purple-800'
  },
  {
    id: 'tt-4',
    classId: 'cls-1',
    day: 'tuesday',
    timeSlot: '08:00 - 10:00',
    subject: 'Éveil Scientifique & Informatique',
    subjectAr: 'الإيقاظ العلمي والإعلامية',
    teacherName: 'Rim Mahjoub',
    teacherNameAr: 'ريم المحجوب',
    room: 'Labo Carthage Info',
    color: 'border-amber-500 bg-amber-50 text-amber-800'
  },
  {
    id: 'tt-5',
    classId: 'cls-1',
    day: 'tuesday',
    timeSlot: '10:15 - 12:00',
    subject: 'Éducation Civique & Histoire-Géo',
    subjectAr: 'التربية المدنية والتاريخ والجغرافيا',
    teacherName: 'Moncef Ayari',
    teacherNameAr: 'منصف العياري',
    room: 'Salle Carthage 101',
    color: 'border-teal-500 bg-teal-50 text-teal-800'
  },
  {
    id: 'tt-6',
    classId: 'cls-1',
    day: 'wednesday',
    timeSlot: '08:00 - 10:00',
    subject: 'Mathématiques & Préparation Pilote',
    subjectAr: 'الرياضيات والإعداد للنموذجي',
    teacherName: 'Béchir Slama',
    teacherNameAr: 'بشير سلامة',
    room: 'Salle Carthage 101',
    color: 'border-blue-500 bg-blue-50 text-blue-800'
  },
  {
    id: 'tt-7',
    classId: 'cls-1',
    day: 'thursday',
    timeSlot: '14:00 - 16:00',
    subject: 'Éducation Physique & Sport',
    subjectAr: 'التربية البدنية والرياضة',
    teacherName: 'Tarek Mejri',
    teacherNameAr: 'طارق الماجري',
    room: 'Terrain Sport Carthage',
    color: 'border-rose-500 bg-rose-50 text-rose-800'
  },
  {
    id: 'tt-8',
    classId: 'cls-1',
    day: 'friday',
    timeSlot: '08:00 - 10:00',
    subject: 'Arts & Musique Tunisienne',
    subjectAr: 'التربية التشكيلية والموسيقى',
    teacherName: 'Ines Ben Amor',
    teacherNameAr: 'إيناس بن عمر',
    room: 'Atelier Didon',
    color: 'border-indigo-500 bg-indigo-50 text-indigo-800'
  }
];

export const mockPayments: PaymentRecord[] = [
  {
    id: 'pay-1',
    studentId: 'stu-1',
    parentId: 'par-1',
    title: 'Frais de scolarité - Février 2025',
    titleAr: 'معلوم الدراسة - فيفري 2025',
    category: 'tuition',
    amount: 380,
    currency: 'DT',
    dueDate: '2025-02-05',
    paidDate: '2025-02-04',
    status: 'paid',
    receiptNumber: 'REC-TN-2025-0248'
  },
  {
    id: 'pay-2',
    studentId: 'stu-1',
    parentId: 'par-1',
    title: 'Abonnement Cantine & Bus Scolaire - Février 2025',
    titleAr: 'اشتراك المطعم والنقل - فيفري 2025',
    category: 'canteen',
    amount: 220,
    currency: 'DT',
    dueDate: '2025-02-05',
    paidDate: '2025-02-04',
    status: 'paid',
    receiptNumber: 'REC-TN-2025-0249'
  },
  {
    id: 'pay-3',
    studentId: 'stu-3',
    parentId: 'par-3',
    title: 'Frais de scolarité - Février 2025',
    titleAr: 'معلوم الدراسة - فيفري 2025',
    category: 'tuition',
    amount: 380,
    currency: 'DT',
    dueDate: '2025-02-05',
    status: 'overdue',
    receiptNumber: 'REC-TN-PEND-3'
  },
  {
    id: 'pay-4',
    studentId: 'stu-5',
    parentId: 'par-4',
    title: 'Frais de scolarité & Bac Pilote - Mars 2025',
    titleAr: 'معلوم الدراسة والباكالوريا - مارس 2025',
    category: 'tuition',
    amount: 450,
    currency: 'DT',
    dueDate: '2025-03-05',
    status: 'pending',
    receiptNumber: 'REC-TN-PEND-4'
  }
];

export const mockCanteenMenu: CanteenDay[] = [
  {
    day: 'Lundi',
    dayAr: 'الإثنين',
    date: '2025-02-17',
    starter: 'Salade tunisienne fraîche (tomates, concombres, oignons, menthe séchée)',
    starterAr: 'سلاطة تونسية طازجة بالنعناع والليمون',
    mainDish: 'Tajine tunisien au poulet fermier et fromage de Béja',
    mainDishAr: 'طاجين تونسي بالدجاج البلدي وجبن باجة',
    dessert: 'Oranges maltaises douces du Cap Bon',
    dessertAr: 'برتقال مالطي حلو من الوطن القبلي',
    calories: 650,
    allergens: ['Œufs', 'Lait']
  },
  {
    day: 'Mardi',
    dayAr: 'الثلاثاء',
    date: '2025-02-18',
    starter: 'Chorba Frik tunisienne légère aux légumes',
    starterAr: 'شربة فريك تونسية خفيفة بالخضار',
    mainDish: 'Filet de daurade grillé à la sauce tomate tunisienne et riz parfumé',
    mainDishAr: 'فيليه سمك وراطة مشوي مع صلصة تونسية وأرز',
    dessert: 'Crème Assida Zgougou légère aux noisettes torréfiées',
    dessertAr: 'عصيدة زقوقو خفيفة بالبوفريوة المحمصة',
    calories: 620,
    allergens: ['Poisson', 'Fruits à coque']
  },
  {
    day: 'Mercredi',
    dayAr: 'الأربعاء',
    date: '2025-02-19',
    starter: 'Salade Méchouia douce garnie au thon et œuf dur',
    starterAr: 'سلاطة مشوية معتدلة بالتن والبيض',
    mainDish: 'Makrouna tunisienne sauce tomate artisanale et bœuf émincé',
    mainDishAr: 'مقرونة تونسية بالصلصة ولحم البقر',
    dessert: 'Salade de fruits frais au sirop de fleur d\'oranger',
    dessertAr: 'سلطة غلال طازجة بماء الزهر',
    calories: 710,
    allergens: ['Gluten', 'Poisson']
  },
  {
    day: 'Jeudi',
    dayAr: 'الخميس',
    date: '2025-02-20',
    starter: 'Soupe veloutée de lentilles corail au cumin',
    starterAr: 'حساء عدس أحمر بالكمون',
    mainDish: 'Ojja tunisienne aux œufs frais de ferme et merguez douce',
    mainDishAr: 'عجة تونسية ببيض المزرعة والمرقاز',
    dessert: 'Yaourt artisanal local au miel de thym',
    dessertAr: 'ياغورت طبيعي بعسل الزعتر',
    calories: 660,
    allergens: ['Œufs', 'Lait']
  },
  {
    day: 'Vendredi',
    dayAr: 'الجمعة',
    date: '2025-02-21',
    starter: 'Rondelles de concombres et radis à l\'huile d\'olive de Sfax',
    starterAr: 'خيار وفجل بزيت زيتون صفاقس البكر',
    mainDish: 'Couscous tunisien traditionnel aux légumes frais et pois chiches',
    mainDishAr: 'كسكسي تونسي أصيل بالخضار الطازجة والحمص',
    dessert: 'Dattes Deglet Nour de Kébili & Tozeur',
    dessertAr: 'دقلة النور الفاخرة من قبلي وتوزر',
    calories: 740,
    allergens: ['Gluten']
  }
];

export const mockTransportRoutes: TransportRoute[] = [
  {
    id: 'bus-1',
    code: 'CIRCUIT-TUNIS-01',
    name: 'Circuit Carthage / La Marsa / Sidi Bou Saïd / Berges du Lac',
    nameAr: 'مسار قرطاج / المرسى / سيدي بوسعيد / ضفاف البحيرة',
    driverName: 'Abdelkader Mathlouthi',
    driverNameAr: 'عبد القادر المثلوثي',
    driverPhone: '+216 98 890 011',
    supervisorName: 'Khadija Riahi',
    supervisorPhone: '+216 20 890 022',
    busPlate: 'TUNIS-214-8890',
    capacity: 32,
    currentStudentCount: 28,
    status: 'on_route',
    currentStopIndex: 2,
    stops: [
      { id: 'stp-1', name: 'Arrêt La Marsa Plage', nameAr: 'محطة المرسى الشاطئ', scheduledTime: '07:25', passed: true },
      { id: 'stp-2', name: 'Arrêt Sidi Bou Saïd Ville', nameAr: 'محطة سيدي بوسعيد المدينة', scheduledTime: '07:40', passed: true },
      { id: 'stp-3', name: 'Arrêt Berges du Lac 2', nameAr: 'محطة ضفاف البحيرة 2', scheduledTime: '07:55', passed: false },
      { id: 'stp-4', name: 'Arrivée Complexe Carthage Byrsa', nameAr: 'الوصول لمجمع قرطاج بيرصا', scheduledTime: '08:15', passed: false }
    ]
  },
  {
    id: 'bus-2',
    code: 'CIRCUIT-ARIANA-02',
    name: 'Circuit Ennasr 2 / El Menzah 9 / Menzah 6 / Ariana Centre',
    nameAr: 'مسار النصر 2 / المنزه 9 / المنزه 6 / أريانة المركز',
    driverName: 'Fathi Ben Amor',
    driverNameAr: 'فتحي بن عمر',
    driverPhone: '+216 50 890 033',
    supervisorName: 'Mounira Slama',
    supervisorPhone: '+216 22 890 044',
    busPlate: 'TUNIS-198-4520',
    capacity: 28,
    currentStudentCount: 22,
    status: 'arrived',
    currentStopIndex: 3,
    stops: [
      { id: 'stp-21', name: 'Arrêt Avenue Hédi Nouira (Ennasr 2)', nameAr: 'محطة شارع الهادي نويرة (النصر 2)', scheduledTime: '07:20', passed: true },
      { id: 'stp-22', name: 'Arrêt El Menzah 9', nameAr: 'محطة المنزه 9', scheduledTime: '07:45', passed: true },
      { id: 'stp-23', name: 'Arrêt Menzah 6', nameAr: 'محطة المنزه 6', scheduledTime: '08:00', passed: true },
      { id: 'stp-24', name: 'Arrivée Établissement Carthage', nameAr: 'الوصول لمؤسسة قرطاج', scheduledTime: '08:20', passed: true }
    ]
  }
];

export const mockWhatsAppLogs: WhatsAppMessageLog[] = [
  {
    id: 'msg-1',
    recipientName: 'Karim Ben Romdhane',
    phone: '+216 98 123 456',
    type: 'payment',
    contentFr: 'Reçu de paiement confirmé : 380 DT pour les frais scolaires de Février.',
    contentAr: 'تأكيد استلام وصل خلاص: 380 د.ت لمعاليم شهر فيفري.',
    timestamp: '2025-02-18 09:15',
    status: 'sent',
    studentName: 'Rayan Ben Romdhane'
  },
  {
    id: 'msg-2',
    recipientName: 'Tarek Jaziri',
    phone: '+216 50 345 678',
    type: 'absence',
    contentFr: 'Avis d\'absence : Youssef Jaziri signalé absent ce matin (08h00).',
    contentAr: 'إشعار غياب: تسجيل غياب يوسف الجزيري هذا الصباح (08:00).',
    timestamp: '2025-02-18 08:45',
    status: 'sent',
    studentName: 'Youssef Jaziri'
  },
  {
    id: 'msg-3',
    recipientName: 'Salma Trabelsi',
    phone: '+216 20 234 567',
    type: 'grade',
    contentFr: 'Félicitations pour la note du Devoir de Synthèse de Salma : 19/20.',
    contentAr: 'تهانينا بحصول سلمى على 19/20 في الفرض التأليفي.',
    timestamp: '2025-02-17 16:30',
    status: 'sent',
    studentName: 'Salma Trabelsi'
  },
  {
    id: 'msg-4',
    recipientName: 'Groupe Parents Ligne Carthage 01',
    phone: '+216 98 890 011',
    type: 'transport',
    contentFr: 'Alerte Bus : Le bus approche de l\'arrêt Berges du Lac 2 dans 5 minutes.',
    contentAr: 'تنبيه الحافلة: اقتراب الحافلة من محطة ضفاف البحيرة 2 خلال 5 دقائق.',
    timestamp: '2025-02-18 07:50',
    status: 'sent',
    studentName: 'Tous les élèves Ligne 1'
  }
];

export const mockHomework: HomeworkItem[] = [
  {
    id: 'hw-1',
    classId: 'cls-1',
    className: '6ème Année de Base (Concours Pilote - A)',
    classNameAr: 'السنة السادسة أساسي (مناظرة النموذجي - أ)',
    teacherId: 'tch-3',
    teacherName: 'Béchir Slama',
    teacherNameAr: 'بشير سلامة',
    subject: 'Mathématiques & Logique',
    subjectAr: 'الرياضيات والتفكير المنطقي',
    title: 'Exercices 14, 15 et 18 p. 68 : Géométrie et aires des polygones',
    titleAr: 'تمارين 14 و15 و18 ص 68: الهندسة ومساحات المضلعات',
    description: 'Résoudre les 3 problèmes de géométrie sur le cahier de cours. Tracer soigneusement les figures avec la règle et le compas en vue du concours pilote.',
    descriptionAr: 'حل المسائل الثلاث في الهندسة على دفتر التمارين. رسم الأشكال بدقة بالمسطرة والبركار استعداداً لمناظرة النموذجي.',
    dueDate: '2025-02-24',
    assignedDate: '2025-02-20',
    estimatedMinutes: 35,
    status: 'active'
  },
  {
    id: 'hw-2',
    classId: 'cls-1',
    className: '6ème Année de Base (Concours Pilote - A)',
    classNameAr: 'السنة السادسة أساسي (مناظرة النموذجي - أ)',
    teacherId: 'tch-1',
    teacherName: 'Moncef Ayari',
    teacherNameAr: 'منصف العياري',
    subject: 'Langue Arabe & Éducation Civique',
    subjectAr: 'اللغة العربية والتربية المدنية',
    title: 'تحرير إنشائي: وصف مشهد ربيعي بالقرية التونسية',
    titleAr: 'تحرير إنشائي: وصف مشهد ربيعي بالقرية التونسية',
    description: 'تحرير فقرة لا تقل عن 12 سطراً مع توظيف أساليب التشبيه والوصف الدقيق وعلامات التنقيط.',
    descriptionAr: 'تحرير فقرة لا تقل عن 12 سطراً مع توظيف أساليب التشبيه والوصف الدقيق وعلامات التنقيط.',
    dueDate: '2025-02-25',
    assignedDate: '2025-02-21',
    estimatedMinutes: 30,
    status: 'active'
  },
  {
    id: 'hw-3',
    classId: 'cls-2',
    className: '9ème Année de Base (Concours Neuvième)',
    classNameAr: 'السنة التاسعة أساسي (مناظرة النوفيام)',
    teacherId: 'tch-2',
    teacherName: 'Sonia Dridi',
    teacherNameAr: 'سنية الدريدي',
    subject: 'Français & Littérature',
    subjectAr: 'اللغة الفرنسية والآداب',
    title: 'Fiche de lecture & Analyse du texte argumentatif',
    titleAr: 'جذاذة قراءة وتحليل نص حجاجي',
    description: 'Lire attentivement le texte n°4 du manuel (page 92) et répondre aux questions de compréhension 1 à 6.',
    descriptionAr: 'قراءة النص رقم 4 في الكتاب المدرسي ص 92 والإجابة عن أسئلة الفهم من 1 إلى 6.',
    dueDate: '2025-02-26',
    assignedDate: '2025-02-21',
    estimatedMinutes: 40,
    status: 'active'
  },
  {
    id: 'hw-4',
    classId: 'cls-2',
    className: '9ème Année de Base (Concours Neuvième)',
    classNameAr: 'السنة التاسعة أساسي (مناظرة النوفيام)',
    teacherId: 'tch-4',
    teacherName: 'Rim Mahjoub',
    teacherNameAr: 'ريم المحجوب',
    subject: 'Sciences Physiques & SVT',
    subjectAr: 'العلوم الفيزيائية وعلوم الحياة',
    title: 'Compte-rendu de laboratoire : Lois de l\'électricité & Circuit RLC',
    titleAr: 'تقرير مخبري: قوانين الكهرباء والدارة RLC',
    description: 'Finaliser le schéma du montage expérimental et calculer l\'intensité du courant selon la loi d\'Ohm.',
    descriptionAr: 'إتمام رسم المخطط التجريبي واحتساب شدة التيار وفق قانون أوم.',
    dueDate: '2025-02-27',
    assignedDate: '2025-02-22',
    estimatedMinutes: 45,
    status: 'active'
  }
];
